Repository Jeck0v/BrowserQuest, pull requests merged in 2025-04, with the labels that each got.

#5 Refactor camera focus logic and enhance game rendering. Update packag…
  client/js/camera.js
  client/js/game.js
  client/js/renderer.js
  package.json
Labels: bug, enhancement

#6 Merge Master to dev/docker
  client/js/camera.js
  client/js/game.js
  client/js/renderer.js
  package.json
Labels: backend

#10 Add Docker support and update configuration files
  Dockerfile
  README.md
  client/config/config_build.json-dist
  client/config/config_local.json-dist
  client/js/config.js
  client/shared
  server/config_local.json-dist
Labels: bug, documentation, enhancement, need review

#12 Security
  Dockerfile
  README.md
  client/README.md
  client/js/gameclient.js
  client/js/lib/bison.js
  package-lock.json
  package.json
  server/README.md
  server/config.json
  server/js/firewall.js
  server/js/main.js
  server/js/player.js
  server/js/worldserver.js
  server/js/ws.js
Labels: documentation, enhancement, need review, frontend, backend

#13 Dev/infra v2
  .idea/.gitignore
  .idea/discord.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/vcs.xml
  browserquest-infra/docs/infra.md
  browserquest-infra/kustomization.yaml
  browserquest-infra/manifests/base/deployment.yaml
  browserquest-infra/manifests/base/hpa.yaml
  browserquest-infra/manifests/base/kustomization.yaml
  browserquest-infra/manifests/base/namespace.yaml
  browserquest-infra/manifests/base/service.yaml
  browserquest-infra/manifests/dualstack/enable-dualstack.md
  browserquest-infra/manifests/ingress/controller.yaml
  browserquest-infra/manifests/ingress/ingress.yaml
  browserquest-infra/manifests/ingress/kustomization.yaml
  browserquest-infra/manifests/kustomization.yaml
  browserquest-infra/manifests/metrics/kustomization.yaml
  browserquest-infra/manifests/metrics/metrics-server.yaml
  browserquest-infra/manifests/metrics/placeholder.yaml
  browserquest-infra/scripts/deploy.bat
  browserquest-infra/scripts/start-minikube.bat
  browserquest-infra/scripts/status.bat
  browserquest-infra/scripts/test-access.bat
  client/.dockerignore
  client/js/gameclient.js
  package.json
  server/config.json
  server/js/area.js
  server/js/checkpoint.js
  server/js/chestarea.js
Labels: enhancement, need review, backend
